ifneq (,${findstring ntel,${PETSC_ARCH}})
  FC_FLAGS+= -diag-disable 6380
endif
#ifneq (,${findstring ntel,${PETSC_ARCH}})
#   FLINKER+= -Wl,-no_pie
#endif

MEF90_INCLUDE=${MEF90_DIR}/objs/${PETSC_ARCH}

ifneq (${SNLP_DIR},)
	FC_FLAGS+= -DMEF90_HAVE_SNLP -I${SNLP_DIR}/include -I${SNLP_DIR}/obj
	C_FLAGS+= -I${SNLP_DIR}/include -I${SNLP_DIR}/obj
	SNLP_LIB:= -L${SNLP_DIR}/lib -lsnlp -lsnlpF90 -Wl,-rpath,${SNLP_DIR}/lib
endif


