### Build: 
###    docker buildx build --platform=linux/x86_64,linux/arm64 -t mef90rocky -f Dockerfile.mef90rocky .

### publish to dockerhub:
### docker tag mef90rocky:latest bourdin/mef90rocky:<tag>
### get tag:
###    cd $PETSC_DIR; git describe --dirty --always --tag
###    docker run -w /opt/HPC/petsc-main mef90rocky:latest git describe --dirty --always --tags

### Start from a basic rocky system
FROM rockylinux:9 AS mef90rockylinux

### install development packages
RUN dnf update -y 
RUN dnf install -y diffutils cmake procps make gcc gcc-c++ gfortran pkgconfig which bzip2 openssh-server openssh-clients wget net-tools git libtool automake autoconf mesa-libGLU libXrender libXcursor libXft fontconfig libXinerama libxkbcommon pcre2-utf16 cpio python3-pip gmp gmp-devel hwloc hwloc-devel vim 

### SYMENGINE
ENV SYMENGINE_ROOT=/opt/HPC/symengine
RUN git clone https://github.com/symengine/symengine.git /opt/HPC/src/symengine
RUN mkdir -p /opt/HPC/src/symengine/build;\
cd /opt/HPC/src/symengine/build;\
cmake -DCMAKE_INSTALL_PREFIX=${SYMENGINE_ROOT} ..;\
make;\
make install

### SYMENGINE-F90
ENV SYMENGINEF90_ROOT=/opt/HPC/symengine-f90
RUN git clone https://github.com/symengine/symengine.f90.git /opt/HPC/src/symengine-f90
RUN mkdir -p /opt/HPC/src/symengine-f90/build;\
cd /opt/HPC/src/symengine-f90/build;\
cmake -DSymEngine_DIR=${SYMENGINE_ROOT} -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=${SYMENGINEF90_ROOT} -DCMAKE_POLICY_VERSION_MINIMUM=3.5 ..;\
make;\
make install

# ### PYTHON / JUPYTER
# RUN apt install -y python3-pip python3-pyaml-env python3-matplotlib jupyter

### PETSC
ENV PETSC_DIR=/opt/HPC/petsc
ENV PETSC_ARCH=arch-rocky9-mpich-O 
ENV PATH=$PETSC_DIR/bin:$PETSC_DIR/$PETSC_ARCH/bin:$PATH
RUN git clone --single-branch --branch release https://gitlab.com/petsc/petsc.git ${PETSC_DIR}

RUN cd ${PETSC_DIR} ;                 \
    ./configure                       \
    --COPTFLAGS='-O3'   \
    --CXXOPTFLAGS='-O3' \
    --FOPTFLAGS='-O3'   \
    CFLAGS+='-Wimplicit-function-declaration -Wunused' \
    FFLAGS+='-ffree-line-length-none -fallow-argument-mismatch -Wunused' \
    --download-fblaslapack=1          \
    --download-exodusii=1             \
    --download-hdf5=1                 \
    --download-hypre=1                \
    --download-metis=1                \
    --download-mpich=1                \
    --download-netcdf=1               \
    --download-ml=1                   \
    --download-parmetis=1             \
    --download-pnetcdf=1              \
    --download-sowing=1               \
    --download-zlib=1                 \
    --with-debugging=0                \
    --with-exodusii-fortran-bindings  \
    --with-shared-libraries=1         \
    --with-x11=1;
RUN cd ${PETSC_DIR}; make PETSC_DIR=${PETSC_DIR} PETSC_ARCH=${PETSC_ARCH} all

### MEF90
ENV MEF90_DIR=/opt/HPC/mef90
ENV PATH=${MEF90_DIR}/bin:${MEF90_DIR}/${PETSC_ARCH}/bin:${PETSC_DIR}/bin:${PETSC_DIR}/${PETSC_ARCH}/bin:$PATH
ENV PYTHONPATH=${MEF90_DIR}/python
RUN git clone --single-branch --branch main https://github.com/bourdin/mef90 ${MEF90_DIR}
RUN cd ${MEF90_DIR} ; make vDef; \
    cd Utils;  make all

