### Build: 
###    docker buildx build --platform=linux/x86_64,linux/arm64 -t mef90ubuntu -f Dockerfile.mef90ubuntu .

### publish to dockerhub:
### docker tag mef90ubuntu:latest bourdin/mef90ubuntu:<tag>
### get tag:
###    cd $PETSC_DIR; git describe --dirty --always --tag
###    docker run -w /opt/HPC/petsc-main mef90ubuntu:latest git describe --dirty --always --tags

### Start from a basic ubuntu system
FROM ubuntu:rolling AS mef90ubuntu

### install development packages
RUN apt update;\
    apt -y upgrade
RUN apt install -y vim cmake libblas-dev libblas64-dev python3 valgrind git gfortran g++;\
    apt install -y liblapack-dev liblapack64-dev gmsh libgmsh-dev autoconf automake libtool;\
    apt install -y libgmp-dev
RUN mkdir -p /opt/HPC/src

### SYMENGINE
ENV SYMENGINE_ROOT=/opt/HPC/symengine
RUN git clone https://github.com/symengine/symengine.git /opt/HPC/src/symengine
RUN mkdir -p /opt/HPC/src/symengine/build;\
cd /opt/HPC/src/symengine/build;\
cmake -DCMAKE_INSTALL_PREFIX=${SYMENGINE_ROOT} ..;\
make;\
make install

### SYMENGINE-F90
ENV SYMENGINEF90_ROOT=/opt/HPC/symengine-f90
RUN git clone https://github.com/symengine/symengine.f90.git /opt/HPC/src/symengine-f90
RUN mkdir -p /opt/HPC/src/symengine-f90/build;\
cd /opt/HPC/src/symengine-f90/build;\
cmake -DSymEngine_DIR=${SYMENGINE_ROOT} -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=${SYMENGINEF90_ROOT} -DCMAKE_POLICY_VERSION_MINIMUM=3.5 ..;\
make;\
make install

### PYTHON / JUPYTER
RUN apt install -y python3-pip python3-pyaml-env python3-matplotlib jupyter

### PETSC
ENV PETSC_DIR=/opt/HPC/petsc
ENV PETSC_ARCH=arch-ubuntu-mpich-O 
ENV PATH=$PETSC_DIR/bin:$PETSC_DIR/$PETSC_ARCH/bin:$PATH
RUN git clone --single-branch --branch release https://gitlab.com/petsc/petsc.git ${PETSC_DIR}

RUN cd ${PETSC_DIR} ;                 \
    ./configure                       \
    --COPTFLAGS='-O3 -mcpu=native'   \
    --CXXOPTFLAGS='-O3 -mcpu=native' \
    --FOPTFLAGS='-O3 -mcpu=native'   \
    CFLAGS+='-Wimplicit-function-declaration -Wunused' \
    FFLAGS+='-ffree-line-length-none -fallow-argument-mismatch -Wunused' \
    --download-exodusii=1             \
    --download-hdf5=1                 \
    --download-hypre=1                \
    --download-metis=1                \
    --download-mpich=1                \
    --download-netcdf=1               \
    --download-ml=1                   \
    --download-parmetis=1             \
    --download-pnetcdf=1              \
    --download-sowing=1               \
    --download-zlib=1                 \
    --with-debugging=0                \
    --with-exodusii-fortran-bindings  \
    --with-shared-libraries=1         \
    --with-x11=1;                     \
    make PETSC_DIR=${PETSC_DIR} PETSC_ARCH=${PETSC_ARCH} all

### MEF90
ENV MEF90_DIR=/opt/HPC/mef90
ENV PATH=${MEF90_DIR}/bin:${MEF90_DIR}/${PETSC_ARCH}/bin:${PETSC_DIR}/bin:${PETSC_DIR}/${PETSC_ARCH}/bin:$PATH
ENV PYTHONPATH=${MEF90_DIR}/python
RUN git clone --single-branch --branch bourdin/removeBags https://github.com/bourdin/mef90 ${MEF90_DIR}
RUN cd ${MEF90_DIR} ; make vDef; \
    cd Utils;  make all

