### Build: 
###    docker build -t intelpetsc -f Dockerfile.intel-hpckit --target intelpetsc .

### publish to dockerhub:
### docker tag ubuntumpichbase:latest bourdin/ubuntumpichbase:latest
### docker push bourdin/ubuntumpichbase:latest
### docker tag ubuntumpichpetsc:latest bourdin/ubuntumpichpetsc:<tag>
### get tag:
###    cd $PETSC_DIR; git describe --dirty --always --tag
###    docker run -w /opt/HPC/petsc-main ubuntumpichpetsc:latest git describe --dirty --always --tags

### Start from a basic ubuntu system and install intel HPC stack

FROM ubuntu:22.04 AS intelpetsc
RUN apt-get update && apt-get upgrade -y
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get install -y --no-install-recommends \
    curl ca-certificates gpg-agent software-properties-common && \
    rm -rf /var/lib/apt/lists/*
# repository to install Intel(R) oneAPI Libraries
RUN curl -fsSL https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB | gpg --dearmor > /usr/share/keyrings/intel-oneapi-archive-keyring.gpg

RUN echo "deb [signed-by=/usr/share/keyrings/intel-oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main " > /etc/apt/sources.list.d/oneAPI.list

RUN apt-get update && apt-get upgrade -y && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    build-essential pkg-config gnupg libarchive13 openssh-server openssh-client wget net-tools git cmake less valgrind gmsh libgmsh-dev autoconf libtool && \
    rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get upgrade -y && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    intel-basekit intel-hpckit && \
    rm -rf /var/lib/apt/lists/*

ENV I_MPI_CC icx
ENV I_MPI_CXX icpx
ENV I_MPI_F77 ifx
ENV I_MPI_F90 ifx
ENV I_MPI_FC ifx

ENV LANG=C.UTF-8
ENV ADVISOR_2024_DIR='/opt/intel/oneapi/advisor/2024.2'
ENV APM='/opt/intel/oneapi/advisor/2024.2/perfmodels'
ENV CCL_CONFIGURATION='cpu_gpu_dpcpp'
ENV CCL_CONFIGURATION_PATH=''
ENV CCL_ROOT='/opt/intel/oneapi/ccl/2021.13'
ENV CLASSPATH='/opt/intel/oneapi/mpi/2021.13/share/java/mpi.jar'
ENV CMAKE_PREFIX_PATH='/opt/intel/oneapi/tbb/2021.13/env/..:/opt/intel/oneapi/mkl/2024.2/lib/cmake:/opt/intel/oneapi/ipp/2021.12/lib/cmake/ipp:/opt/intel/oneapi/dpl/2022.6/lib/cmake/oneDPL:/opt/intel/oneapi/dnnl/2024.2/lib/cmake:/opt/intel/oneapi/dal/2024.5:/opt/intel/oneapi/compiler/2024.2'
ENV CMPLR_ROOT='/opt/intel/oneapi/compiler/2024.2'
ENV CPATH='/opt/intel/oneapi/tbb/2021.13/env/../include:/opt/intel/oneapi/mpi/2021.13/include:/opt/intel/oneapi/mkl/2024.2/include:/opt/intel/oneapi/ippcp/2021.12/include:/opt/intel/oneapi/ipp/2021.12/include:/opt/intel/oneapi/dpl/2022.6/include:/opt/intel/oneapi/dpcpp-ct/2024.2/include:/opt/intel/oneapi/dnnl/2024.2/include:/opt/intel/oneapi/dev-utilities/2024.2/include:/opt/intel/oneapi/dal/2024.5/include/dal:/opt/intel/oneapi/ccl/2021.13/include'
ENV DALROOT='/opt/intel/oneapi/dal/2024.5'
ENV DAL_MAJOR_BINARY='2'
ENV DAL_MINOR_BINARY='0'
ENV DIAGUTIL_PATH='/opt/intel/oneapi/dpcpp-ct/2024.2/etc/dpct/sys_check/sys_check.sh:/opt/intel/oneapi/debugger/2024.2/etc/debugger/sys_check/sys_check.py:/opt/intel/oneapi/compiler/2024.2/etc/compiler/sys_check/sys_check.sh'
ENV DNNLROOT='/opt/intel/oneapi/dnnl/2024.2'
ENV DPL_ROOT='/opt/intel/oneapi/dpl/2022.6'
ENV FI_PROVIDER_PATH='/opt/intel/oneapi/mpi/2021.13/opt/mpi/libfabric/lib/prov:/usr/lib/x86_64-linux-gnu/libfabric'
ENV GDB_INFO='/opt/intel/oneapi/debugger/2024.2/share/info/'
ENV INFOPATH='/opt/intel/oneapi/debugger/2024.2/share/info'
ENV INTEL_PYTHONHOME='/opt/intel/oneapi/debugger/2024.2/opt/debugger'
ENV IPPCP_TARGET_ARCH='intel64'
ENV IPPCRYPTOROOT='/opt/intel/oneapi/ippcp/2021.12'
ENV IPPROOT='/opt/intel/oneapi/ipp/2021.12'
ENV IPP_TARGET_ARCH='intel64'
ENV I_MPI_ROOT='/opt/intel/oneapi/mpi/2021.13'
ENV LD_LIBRARY_PATH='/opt/intel/oneapi/tbb/2021.13/env/../lib/intel64/gcc4.8:/opt/intel/oneapi/mpi/2021.13/opt/mpi/libfabric/lib:/opt/intel/oneapi/mpi/2021.13/lib:/opt/intel/oneapi/mkl/2024.2/lib:/opt/intel/oneapi/ippcp/2021.12/lib/:/opt/intel/oneapi/ipp/2021.12/lib:/opt/intel/oneapi/dpl/2022.6/lib:/opt/intel/oneapi/dnnl/2024.2/lib:/opt/intel/oneapi/debugger/2024.2/opt/debugger/lib:/opt/intel/oneapi/dal/2024.5/lib:/opt/intel/oneapi/compiler/2024.2/opt/compiler/lib:/opt/intel/oneapi/compiler/2024.2/lib:/opt/intel/oneapi/ccl/2021.13/lib/'
ENV LIBRARY_PATH='/opt/intel/oneapi/tbb/2021.13/env/../lib/intel64/gcc4.8:/opt/intel/oneapi/mpi/2021.13/lib:/opt/intel/oneapi/mkl/2024.2/lib/:/opt/intel/oneapi/ippcp/2021.12/lib/:/opt/intel/oneapi/ipp/2021.12/lib:/opt/intel/oneapi/dpl/2022.6/lib:/opt/intel/oneapi/dnnl/2024.2/lib:/opt/intel/oneapi/dal/2024.5/lib:/opt/intel/oneapi/compiler/2024.2/lib:/opt/intel/oneapi/ccl/2021.13/lib/'
ENV MANPATH='/opt/intel/oneapi/mpi/2021.13/share/man:/opt/intel/oneapi/debugger/2024.2/share/man:/opt/intel/oneapi/compiler/2024.2/share/man:'
ENV MKLROOT='/opt/intel/oneapi/mkl/2024.2'
ENV NLSPATH='/opt/intel/oneapi/mkl/2024.2/share/locale/%l_%t/%N:/opt/intel/oneapi/compiler/2024.2/lib/compiler/locale/%l_%t/%N'
ENV OCL_ICD_FILENAMES='/opt/intel/oneapi/compiler/2024.2/lib/libintelocl.so'
ENV ONEAPI_ROOT='/opt/intel/oneapi'
ENV PATH='/opt/intel/oneapi/vtune/2024.2/bin64:/opt/intel/oneapi/mpi/2021.13/bin:/opt/intel/oneapi/mkl/2024.2/bin/:/opt/intel/oneapi/dpcpp-ct/2024.2/bin:/opt/intel/oneapi/dev-utilities/2024.2/bin:/opt/intel/oneapi/debugger/2024.2/opt/debugger/bin:/opt/intel/oneapi/compiler/2024.2/bin:/opt/intel/oneapi/advisor/2024.2/bin64:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
ENV PKG_CONFIG_PATH='/opt/intel/oneapi/vtune/2024.2/include/pkgconfig/lib64:/opt/intel/oneapi/tbb/2021.13/env/../lib/pkgconfig:/opt/intel/oneapi/mpi/2021.13/lib/pkgconfig:/opt/intel/oneapi/mkl/2024.2/lib/pkgconfig:/opt/intel/oneapi/ippcp/2021.12/lib/pkgconfig:/opt/intel/oneapi/dpl/2022.6/lib/pkgconfig:/opt/intel/oneapi/dnnl/2024.2/lib/pkgconfig:/opt/intel/oneapi/dal/2024.5/lib/pkgconfig:/opt/intel/oneapi/compiler/2024.2/lib/pkgconfig:/opt/intel/oneapi/ccl/2021.13/lib/pkgconfig/:/opt/intel/oneapi/advisor/2024.2/include/pkgconfig/lib64:'
ENV PYTHONPATH='/opt/intel/oneapi/advisor/2024.2/pythonapi'
ENV SETVARS_COMPLETED='1'
ENV TBBROOT='/opt/intel/oneapi/tbb/2021.13/env/..'
ENV VTUNE_PROFILER_2024_DIR='/opt/intel/oneapi/vtune/2024.2'
ENV VTUNE_PROFILER_DIR='/opt/intel/oneapi/vtune/2024.2'

ENV PETSC_DIR /opt/HPC/petsc-main
ENV PATH $PETSC_DIR/bin:$PATH

RUN mkdir -p /opt/HPC
RUN git clone --single-branch --branch main https://gitlab.com/petsc/petsc.git ${PETSC_DIR}

ENV PETSC_ARCH arch-intelHPC-g 
RUN cd ${PETSC_DIR} ;                 \
    ./configure                       \
    --download-chaco=1                \
    --download-exodusii=1             \
    --download-hdf5=1                 \
    --download-hypre=1                \
    --download-metis=1                \
    --download-netcdf=1               \
    --download-ml=1                   \
    --download-parmetis=1             \
    --download-pnetcdf=1              \
    --download-zlib=1                 \
    --with-debugging=1                \
    --with-exodusii-fortran-bindings  \
    --with-shared-libraries=1         \
    --with-x11=1;                     \
    make PETSC_DIR=${PETSC_DIR} PETSC_ARCH=arch-intelHPC-g all

# ENV PETSC_ARCH arch-intelHPC-O 
# RUN cd ${PETSC_DIR} ;                 \
#     ./configure                       \
#     --COPTFLAGS='-O3 -mcpu=native'    \
#     --CXXOPTFLAGS='-O3 -mcpu=native'  \
#     --FOPTFLAGS='-O3 -mcpu=native'    \
#     --download-chaco=1                \
#     --download-ctetgen=1              \
#     --download-exodusii=1             \
#     --download-hdf5=1                 \
#     --download-hypre=1                \
#     --download-metis=1                \
#     --download-netcdf=1               \
#     --download-ml=1                   \
#     --download-parmetis=1             \
#     --download-pnetcdf=1              \
#     --download-scalapack              \
#     --download-superlu=1              \
#     --download-triangle=1             \
#     --download-zlib=1                 \
#     --with-debugging=0                \
#     --with-exodusii-fortran-bindings  \
#     --with-shared-libraries=1         \
#     --with-x11=1;                     \
#     make PETSC_DIR=${PETSC_DIR} PETSC_ARCH=arch-intelHPC-O all
