### Build: 
###    docker buildx build --platform=linux/x86_64,linux/arm64 -t ubuntumpichpetsc -f Dockerfile.ubuntu-petsc-mpich --target ubuntumpichpetsc .

### publish to dockerhub:
### docker tag ubuntumpichbase:latest bourdin/ubuntumpichbase:latest
### docker push bourdin/ubuntumpichbase:latest
### docker tag ubuntumpichpetsc:latest bourdin/ubuntumpichpetsc:<tag>
### get tag:
###    cd $PETSC_DIR; git describe --dirty --always --tag
###    docker run -w /opt/HPC/petsc-main ubuntumpichpetsc:latest git describe --dirty --always --tags

### Start from a basic ubuntu system with mpich-3.2
# Use an official Python runtime as a parent image
FROM ubuntu:rolling AS ubuntumpichpetsc

### install development packages
RUN apt update;\
    apt -y upgrade
RUN apt install -y vim cmake libblas-dev libblas64-dev python3 valgrind valgrind-mpi git gfortran g++;\
    apt install -y liblapack-dev liblapack64-dev gmsh libgmsh-dev autoconf automake libtool

ENV PETSC_DIR=/opt/HPC/petsc-main
ENV PATH=$PETSC_DIR/bin:$PATH

RUN mkdir -p /opt/HPC
RUN git clone --single-branch --branch main https://gitlab.com/petsc/petsc.git ${PETSC_DIR}

ENV PETSC_ARCH=arch-ubuntu-mpich-O 
RUN cd ${PETSC_DIR} ;                 \
    ./configure                       \
    --CFLAGS='-Wimplicit-function-declaration -Wunused -Wuninitialized' \
    --FFLAGS='-ffree-line-length-none -fallow-argument-mismatch -Wunused -Wuninitialized' \
    --COPTFLAGS='-O3 -march=native'    \
    --CXXOPTFLAGS='-O3 -march=native'  \
    --FOPTFLAGS='-O3 -march=native'    \
    --download-chaco=0                \
    --download-ctetgen=0              \
    --download-exodusii=1             \
    --download-hdf5=1                 \
    --download-hypre=1                \
    --download-metis=1                \
    --download-mpich=1                \
    --download-netcdf=1               \
    --download-ml=1                   \
    --download-parmetis=1             \
    --download-pnetcdf=1              \
    --download-scalapack=0            \
    --download-superlu=0              \
    --download-triangle=0             \
    --download-zlib=1                 \
    --with-debugging=0                \
    --with-exodusii-fortran-bindings  \
    --with-shared-libraries=1         \
    --with-x11=1;                     \
    make PETSC_DIR=${PETSC_DIR} PETSC_ARCH=${PETSC_ARCH} all

FROM ubuntumpichpetsc AS mef90ubuntu
RUN apt install -y gmsh

ENV MEF90_DIR=/opt/HPC/mef90
ENV PATH=${MEF90_DIR}/bin:${MEF90_DIR}/${PETSC_ARCH}/bin:${PETSC_DIR}/bin:${PETSC_DIR}/${PETSC_ARCH}/bin:$PATH
RUN git clone --single-branch --branch dmplex https://github.com/bourdin/mef90 ${MEF90_DIR}
RUN cd ${MEF90_DIR} ; make vDef; \
    cd Utils;  make all

ENV PYTHONPATH=${MEF90_DIR}/python
RUN apt install -y python3-pip python3-pyaml-env python3-matplotlib
