include ${PETSC_DIR}/conf/rules
include ${PETSC_DIR}/conf/variables

ifneq (,$(findstring gcc,$(PETSC_ARCH)))
        FC_FLAGS += -ffree-line-length-none -ffixed-line-length-none  -ffree-form
endif


TestNewSieve:   TestNewSieve.o
	-${FLINKER} -o TestNewSieve TestNewSieve.o ${PETSC_FORTRAN_LIB} ${PETSC_LIB}
