#!/bin/bash
#$ -S /bin/bash
#$ -o SGEOUTPUT/$JOB_NAME.o$JOB_ID
#$ -e SGEOUTPUT/$JOB_NAME.e$JOB_ID
### stocke les sorties stdout et stderr
##
#$ -M leon@dalembert.upmc.fr

#$ -m bea

#$ -cwd
#$ -V
##
## calcul parallele sur n processeurs
##
#$ -pe openmpi64 10
### tourne sur 4 processeurs

#$ -l qname=para288_lg1

###$ -l h_rt_min=400
#$ -N BAR2D
####set -x	# Echo commands, use "set echo" with csh

python2.5 RunTraction.py  --tmax 5 --epsilon .05 --meshsize .01 --numproc $NSLOTS --numsteps 10
