MEF90_DEFMECH_OBJS = ${MEF90_DIR}/${PETSC_ARCH}/objs/m_MEF90_DefMechClass.o                \
                     ${MEF90_DIR}/${PETSC_ARCH}/objs/m_MEF90_DefMechSplitClass.o         \
                     ${MEF90_DIR}/${PETSC_ARCH}/objs/m_MEF90_DefMechSplit.o              \
                     ${MEF90_DIR}/${PETSC_ARCH}/objs/m_MEF90_DefMechSplitNone.o          \
                     ${MEF90_DIR}/${PETSC_ARCH}/objs/m_MEF90_DefMechSplitHD.o            \
                     ${MEF90_DIR}/${PETSC_ARCH}/objs/m_MEF90_DefMechSplitDeviatoric.o    \
                     ${MEF90_DIR}/${PETSC_ARCH}/objs/m_MEF90_DefMechAssembly2D.o         \
                     ${MEF90_DIR}/${PETSC_ARCH}/objs/m_MEF90_DefMechAssembly3D.o         \
                     ${MEF90_DIR}/${PETSC_ARCH}/objs/m_MEF90_DefMechPlasticity2D.o       \
                     ${MEF90_DIR}/${PETSC_ARCH}/objs/m_MEF90_DefMechPlasticity3D.o       \
                     ${MEF90_DIR}/${PETSC_ARCH}/objs/m_MEF90_DefMechATClass.o            \
                     ${MEF90_DIR}/${PETSC_ARCH}/objs/m_MEF90_DefMechAT1.o                \
                     ${MEF90_DIR}/${PETSC_ARCH}/objs/m_MEF90_DefMechAT1Exp.o             \
                     ${MEF90_DIR}/${PETSC_ARCH}/objs/m_MEF90_DefMechAT2.o                \
                     ${MEF90_DIR}/${PETSC_ARCH}/objs/m_MEF90_DefMechATKKL.o              \
                     ${MEF90_DIR}/${PETSC_ARCH}/objs/m_MEF90_DefMechAT.o                 \
                     ${MEF90_DIR}/${PETSC_ARCH}/objs/m_MEF90_DefMech.o