MEF90_DEFMECH_OBJS = ${MEF90_DIR}/objs/${PETSC_ARCH}/m_MEF90_DefMechCtx.o        \
                     ${MEF90_DIR}/objs/${PETSC_ARCH}/m_MEF90_DefMechAssembly2D.o \
                     ${MEF90_DIR}/objs/${PETSC_ARCH}/m_MEF90_DefMechAssembly3D.o \
                     ${MEF90_DIR}/objs/${PETSC_ARCH}/m_MEF90_DefMechPlasticity2D.o \
                     ${MEF90_DIR}/objs/${PETSC_ARCH}/m_MEF90_DefMechPlasticity3D.o \
                     ${MEF90_DIR}/objs/${PETSC_ARCH}/m_MEF90_DefMechSplitMasonry2D.o \
                     ${MEF90_DIR}/objs/${PETSC_ARCH}/m_MEF90_DefMechSplitMasonry3D.o \
                     ${MEF90_DIR}/objs/${PETSC_ARCH}/m_MEF90_DefMech.o
