MEF90_DEFMECH_OBJS = ${MEF90_DIR}/objs/${PETSC_ARCH}/m_MEF90_DefMechCtx.o \
                     ${MEF90_DIR}/objs/${PETSC_ARCH}/m_MEF90_DefMechAssembly2D.o\
                     ${MEF90_DIR}/objs/${PETSC_ARCH}/m_MEF90_DefMechAssembly3D.o\
                     ${MEF90_DIR}/objs/${PETSC_ARCH}/m_MEF90_DefMechGradientDamageImplementation2D.o\
                     ${MEF90_DIR}/objs/${PETSC_ARCH}/m_MEF90_DefMechGradientDamageImplementation3D.o\
                     ${MEF90_DIR}/objs/${PETSC_ARCH}/m_MEF90_DefMechGradientDamageInterface.o\
                     ${MEF90_DIR}/objs/${PETSC_ARCH}/m_MEF90_DefMech.o
