BIN = SimplePoisson 
#Order is important
SRCS = \
	   m_Poisson.F90  \
	   m_MEF_Integrate.F90  \
	   m_TransientHeat.F90 \
	   SimplePoisson.F90   \
#	   TransientHeat.F90  

MEF90_INCS += -I${OBJDIR} 

include ../Makefile.inc  
