BIN = VarFilmQS 
#Order is important
SRCS = m_VarFilmQS_Types.F90  \
	   m_VarFilmQS_Post.F90  \
	   m_VarFilmQS_V.F90 \
	   m_VarFilmQS_W.F90  \
	   m_VarFilmQS_U.F90  \
	   m_VarFilmQS.F90  


MEF90_INCS += -I${OBJDIR} ${TAO_INCLUDE} 
TAO =True

include ../Makefile.inc  
